repos:
  - repo: https://github.com/fsouza/mirrors-pyright
    rev: v1.1.402
    hooks:
      - id: pyright
        args: [--project=pyrightconfig.json]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml"]
  - repo: local
    hooks:
      - id: pytest-push
        name: pytest (pre-push)
        entry: pytest -q --maxfail=1 --disable-warnings
        language: system
        stages: [pre-push]
